################
# Test environment Docker Compose file
#
# This compose file is only good for automated testing.
#
# docker exec --workdir=/app unmanic-testenv pytest --log-cli-level=INFO
#


version: '2'

services:
  unmanic-testenv:
    container_name: unmanic-testenv
    image: josh5/unmanic:latest
    ports:
      - 8888:8888
    environment:
      - PUID=1000
      - PGID=1000
      - DEBUGGING=false
      - NUMBER_OF_WORKERS=2
      - SCHEDULE_FULL_SCAN_MINS=10
      - RUN_FULL_SCAN_ON_START=false
    volumes:
      - ../tests/tmp/cache:/tmp/unmanic
      - ../tests/tmp/tests/tmp/library:/library
      - ../tests/tmp/tests/tmp/config:/config
      - ../tests:/app/tests
