name: Docker Image CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build python dist package
      run: |
        python ./setup.py bdist_egg
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag josh5/unmanic:latest --tag josh5/unmanic:$(date +%s)
